name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: bats test
  
    - run: sudo apt-get install -y bats
    - uses: actions/checkout@v2
    - run: bats ex3/test.sh
