name: test bats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2
        with:
          MY_NAME: "Mona"
      - name: install bats
        run: sudo apt-get install -y bats
      - uses: actions/checkout@v2
      - run: chmod 755 ./ex3/entrypoint.sh
      - name: bats test
        run: bats ex3/test.sh
